In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import datetime

plt.rcParams["figure.figsize"] = (20,10)

## State policies

In [2]:
state_df = pd.read_csv('state_policies.csv')

In [3]:
state_df

,state_id,county,fips_code,policy_level,date,policy_type,start_stop,comments,source,total_phases
0,HI,NaN,NaN,state,2020-05-18,Manufacturing,start,"Policy_Details: Open with adjusted ""Safe Pract...",sip_submission_form: https://governor.hawaii.g...,NaN
1,TX,Kinney,48271.0,county,2020-07-03,Mask Requirement,start,Policy_Details: County is approved to be exemp...,sip_submission_form: https://tdem.texas.gov/ga...,NaN
2,ID,Custer,16037.0,county,2020-10-27,Phase 3,start,Policy_Details: No greater than 50 people at i...,sip_submission_form: https://coronavirus.idaho...,4.0
3,UT,Wayne,49055.0,county,2020-11-24,Phase 1,start,Policy_Details: Restrictions for highest level...,sip_submission_form: https://coronavirus.utah....,3.0
4,TX,Borden,48033.0,county,2020-07-03,Mask Requirement,start,Policy_Details: County is approved to be exemp...,sip_submission_form: https://tdem.texas.gov/ga...,NaN
...,...,...,...,...,...,...,...,...,...,...
3803,MI,Grand Traverse,26055.0,county,2020-07-31,Outdoor and Recreation,start,"Policy_Details: indoor swimming pools, arcade...",sip_submission_form: https://www.michigan.gov/...,NaN
3804,NJ,NaN,NaN,state,2020-06-15,Food and Drink,start,Policy_Details: Outdoor dining (beginning on J...,sip_submission_form: https://covid19.nj.gov/fa...,NaN
3805,MI,Benzie,26019.0,county,2020-07-31,Outdoor and Recreation,start,"Policy_Details: indoor swimming pools, arcade...",sip_submission_form: https://www.michigan.gov/...,NaN
3806,TX,Liberty County,48291.0,county,2020-04-30,Shelter in Place,stop,Liberty County Policy End,wikidata,NaN
3807,MO,Johnson County,29101.0,county,2020-04-30,Shelter in Place,stop,Johnson County Policy End,wikidata,NaN

In [4]:
state_df['state_id'].nunique() # 55 unique states???

55

In [5]:
state_df = state_df[state_df['policy_level']=='state'] # primarily will concern with state level policies

In [6]:
state_df = state_df.drop(columns=['county', 'fips_code', 'source', 'policy_level'])

In [7]:
state_df

,state_id,date,policy_type,start_stop,comments,total_phases
0,HI,2020-05-18,Manufacturing,start,"Policy_Details: Open with adjusted ""Safe Pract...",NaN
5,IA,2020-05-28,Childcare (K-12),start,"Policy_Details: 50% capacity Phase Level: 2, P...",NaN
7,IN,2020-05-04,Phase 2,start,Policy_Details: manufacturering & industrial o...,5.0
9,TN,2020-03-25,Stop Initiation Of Evictions Overall Or Due To...,start,Other measures and details for this policy inc...,NaN
10,VT,2020-03-20,Allow Audio Only Telehealth,start,Other measures and details for this policy inc...,NaN
...,...,...,...,...,...,...
3793,VT,0020-05-04,Resumed Elective Medical Procedures,start,Other measures and details for this policy inc...,NaN
3797,NH,2020-05-01,Mandate Face Mask Use By All Individuals In Pu...,start,Other measures and details for this policy inc...,NaN
3798,NM,2020-04-30,Food and Drink,start,Policy_Details: New Mexico's stay at home rest...,NaN
3800,MA,2020-06-01,Phase 2,start,Policy_Details: non-construction-related home ...,4.0
3804,NJ,2020-06-15,Food and Drink,start,Policy_Details: Outdoor dining (beginning on J...,NaN

In [8]:
state_df['policy_type'].nunique() # 59
state_df['policy_type'].unique()

array(['Manufacturing', 'Childcare (K-12)', 'Phase 2',
       'Stop Initiation Of Evictions Overall Or Due To Covid Related Issues',
       'Allow Audio Only Telehealth', 'Entertainment', 'Phase 3',
       'Non-Essential Businesses',
       'Mandate Face Mask Use By All Individuals In Public Spaces',
       'Modify Medicaid Requirements With 1135 Waivers Date Of CMS Approval',
       'Outdoor and Recreation', 'State of Emergency',
       'Suspended Elective Medical Dental Procedures',
       'Allow Expand Medicaid Telehealth Coverage', 'Shelter in Place',
       'Mask Requirement', 'Day Care',
       'Resumed Elective Medical Procedures', 'Houses of Worship',
       'Travel',
       'Mandate Face Mask Use By All Individuals In Public Facing Businesses',
       'museums', 'Nursing Homes', 'Phase 1', 'New Phase',
       'Personal Care', 'libraries', 'Gyms', 'Food and Drink',
       'Stop Enforcement Of Evictions Overall Or Due To Covid Related Issues',
       'Reopened ACA Enrollment Using a Special Enrollment Period',
       'Order Freezing Utility Shut Offs', 'Graduation', 'Gatherings',
       'Colleges & Universities', 'Phase 4', 'Election',
       'Froze Mortgage Payments', 'State of Emergency/Funds',
       'Graduation Ceremony guidelines', 'Medical',
       'Residential Overnight Camps', 'Health Risk Status',
       'Public Gatherings', 'Phase 5',
       'Renter Grace Period Or Use Of Security Deposit To Pay Rent',
       'Updated Guidelines', 'Executive Order', 'Phase 2, 3', 'travel',
       'higher education', 'Quarantine', 'Nursing Home Visitations',
       'training jobs', 'traveler from out of state',
       'Alternative Care Facilities ', 'Education', 'Phase 3 Step 2',
       'Day camps/overnight camps'], dtype=object)

In [9]:
state_df['date'] = state_df['date'].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d').date())

In [10]:
state_df['date']

0       2020-05-18
5       2020-05-28
7       2020-05-04
9       2020-03-25
10      2020-03-20
           ...
3793    0020-05-04
3797    2020-05-01
3798    2020-04-30
3800    2020-06-01
3804    2020-06-15
Name: date, Length: 1677, dtype: object

In [11]:
state_df['start_stop'].value_counts()

start    1221
stop      456
Name: start_stop, dtype: int64

In [12]:
state_df['total_phases'].value_counts()

3.0    110
4.0     75
5.0     59
2.0      8
6.0      8
1.0      2
Name: total_phases, dtype: int64

In [13]:
state_df['comments'].value_counts()

Other measures and details for this policy include: alcohol liquor stores open, keep firearms sellers open                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            147
Other measures and details for this policy include: alcohol liquor stores open, keep firearms sellers open, made effort to limit abortion access                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      123
Other measures and details for this policy include: alcohol liquor stores open, keep firearms sellers open, paid sick leave                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            91
Other measures and details for this policy include: religious gatherings exempt without clear social distance mandate, alcohol liquor stores open, keep firearms sellers open                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          84
Other measures and details for this policy include: religious gatherings exempt without clear social distance mandate, alcohol liquor stores open, keep firearms sellers open, made effort to limit abortion access                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    71
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ...
Policy_Details: -Employees and patrons must wear a cloth face covering at all times\r\n-Gloves must be worn only as indicated per routine job responsibilities.\r\nâ€¢Perform frequent hand hygiene (with soap and water or alcohol-based hand sanitizer).\r\n-Avoid Close Contact and Reduce Touch points for Patrons and Employees(indoor barriers, encourage online shopping, make one way paths etc.)\r\n-Employers must perform screening (e.g., symptom questionnaires) of employees daily,\r\nprior to entering the business, over the phone or in person\r\n-sick employees must not enter workplace ; if sick at work must immediately be separated and sent home.\r\n-Limits the number of persons in the establishment at 50% of occupancy as specified on the Certificate of Occupancy and establishes processes.   Source information: https://coronavirus.dc.gov/sites/default/files/dc/sites/coronavirus/page_content/attachments/COVID-19_DC_Health_Guidance_for_Retail_08202020.pdf      1
Stay at home, effective at 12:01 a.m. MDT, March 27 until at least May 1 Only certain counties                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Policy_Details: Public Health Emergency Order signed 8/28 by New Mexico Department of Health extending and amending the March 23, 2020, April 6, 2020, April 11, 2020, April 30, 2020, May 5, 2020, May 15, 2020, May 27, 2020, June 1, 2020, June 12, 2020, June 15, 2020, June 30, 2020, July 13, 2020, and July 30, 2020 Public Health Emergency Orders with no major changes, but houses of worship now allowed to hold services at 40% capacity (previously 25% as of 7/30 order)   Source information: https://cv.nmhealth.org/wp-content/uploads/2020/08/082820-PHO.pdf                                                                                                                                                                                                                                                                                                                                                                                                                          1
Policy_Details: All business can reopen.\r\nMass gatherings up to 45 people.\r\nNonessential travel may resume.   Source information: https://covid.ks.gov/wp-content/uploads/2020/05/Reopen-Kansas-Framework-v7.pdf                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Policy_Details: Governor Brian Kemp Executive Order: Stay at home order was extended, but only for elderly and medically compromised.  Indoor movie theaters and bowling alleys may reopen given guidelines.\r\nCease in-person operations of bars, live performances, amusement parks/perfomance venues.   Phase Level: 1, Phase Details Source information: https://www.georgia.org/covid19bizguide, https://gov.georgia.gov/executive-action/executive-orders/2020-executive-orders (click on order from 4/23 to download pdf)                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Name: comments, Length: 739, dtype: int64

In [ ]:
state_df['state'] = state_df['state_id']

In [61]:
state_df

,date,policy_type,start_stop,comments,total_phases,state
0,2020-05-18,Manufacturing,start,"Policy_Details: Open with adjusted ""Safe Pract...",NaN,HI
5,2020-05-28,Childcare (K-12),start,"Policy_Details: 50% capacity Phase Level: 2, P...",NaN,IA
7,2020-05-04,Phase 2,start,Policy_Details: manufacturering & industrial o...,5.0,IN
9,2020-03-25,Stop Initiation Of Evictions Overall Or Due To...,start,Other measures and details for this policy inc...,NaN,TN
10,2020-03-20,Allow Audio Only Telehealth,start,Other measures and details for this policy inc...,NaN,VT
...,...,...,...,...,...,...
3793,0020-05-04,Resumed Elective Medical Procedures,start,Other measures and details for this policy inc...,NaN,VT
3797,2020-05-01,Mandate Face Mask Use By All Individuals In Pu...,start,Other measures and details for this policy inc...,NaN,NH
3798,2020-04-30,Food and Drink,start,Policy_Details: New Mexico's stay at home rest...,NaN,NM
3800,2020-06-01,Phase 2,start,Policy_Details: non-construction-related home ...,4.0,MA
3804,2020-06-15,Food and Drink,start,Policy_Details: Outdoor dining (beginning on J...,NaN,NJ

In [62]:
state_df.to_csv('cleaned_state_policies.csv')

## State history

In [14]:
state_hist = pd.read_csv('state_history.csv')

In [15]:
state_hist

,date,state,dataQualityGrade,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2021-01-15,AK,A,229.0,NaN,1,NaN,1152.0,1152.0,77.0,...,1389226.0,6950,NaN,NaN,NaN,NaN,NaN,0,1389226.0,6950
1,2021-01-15,AL,A,6030.0,5038.0,85,992.0,38763.0,38763.0,2863.0,...,2012213.0,12520,NaN,NaN,95644.0,NaN,2012213.0,12520,NaN,0
2,2021-01-15,AR,A+,4263.0,3525.0,35,738.0,12598.0,12598.0,1314.0,...,2248612.0,14768,NaN,NaN,NaN,307478.0,NaN,0,2248612.0,14768
3,2021-01-15,AS,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,...,2140.0,0,NaN,NaN,NaN,NaN,NaN,0,2140.0,0
4,2021-01-15,AZ,A+,11040.0,9931.0,185,1109.0,45665.0,45665.0,4866.0,...,5912271.0,58182,402939.0,NaN,NaN,NaN,3173905.0,20858,5912271.0,58182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17909,2020-01-17,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17910,2020-01-16,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17911,2020-01-15,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17912,2020-01-14,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17913,2020-01-13,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [16]:
state_hist['date'].nunique()

369

In [17]:
state_hist['date'] = state_hist['date'].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d').date())

In [18]:
state_hist['date']

0        2021-01-15
1        2021-01-15
2        2021-01-15
3        2021-01-15
4        2021-01-15
            ...
17909    2020-01-17
17910    2020-01-16
17911    2020-01-15
17912    2020-01-14
17913    2020-01-13
Name: date, Length: 17914, dtype: object

In [19]:
state_hist.isnull()

,date,state,dataQualityGrade,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,False,False,False,False,True,False,True,False,False,False,...,False,False,True,True,True,True,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,False,True,False,False,False
3,False,False,True,False,True,False,True,True,True,True,...,False,False,True,True,True,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17909,False,False,True,True,True,False,True,True,True,True,...,True,False,True,True,True,True,True,False,True,False
17910,False,False,True,True,True,False,True,True,True,True,...,True,False,True,True,True,True,True,False,True,False
17911,False,False,True,True,True,False,True,True,True,True,...,True,False,True,True,True,True,True,False,True,False
17912,False,False,True,True,True,False,True,True,True,True,...,True,False,True,True,True,True,True,False,True,False
17913,False,False,True,True,True,False,True,True,True,True,...,True,False,True,True,True,True,True,False,True,False

In [29]:
state_hist

,date,state,dataQualityGrade,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2021-01-15,AK,A,229.0,NaN,1,NaN,1152.0,1152.0,77.0,...,1389226.0,6950,NaN,NaN,NaN,NaN,NaN,0,1389226.0,6950
1,2021-01-15,AL,A,6030.0,5038.0,85,992.0,38763.0,38763.0,2863.0,...,2012213.0,12520,NaN,NaN,95644.0,NaN,2012213.0,12520,NaN,0
2,2021-01-15,AR,A+,4263.0,3525.0,35,738.0,12598.0,12598.0,1314.0,...,2248612.0,14768,NaN,NaN,NaN,307478.0,NaN,0,2248612.0,14768
3,2021-01-15,AS,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,...,2140.0,0,NaN,NaN,NaN,NaN,NaN,0,2140.0,0
4,2021-01-15,AZ,A+,11040.0,9931.0,185,1109.0,45665.0,45665.0,4866.0,...,5912271.0,58182,402939.0,NaN,NaN,NaN,3173905.0,20858,5912271.0,58182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17909,2020-01-17,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17910,2020-01-16,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17911,2020-01-15,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17912,2020-01-14,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
17913,2020-01-13,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0

Information on grades  :  https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRL2zG1o-qj9l2sl19d1lj1oHd6WbkJ0ukFwN04a_ms_ANUdgxTMpI7AF-gbQzwOSreJUDx6PEK7Vnq/pubhtml

In [32]:
state_hist['dataQualityGrade'].isnull().sum()

1306

In [34]:
state_hist = state_hist.dropna(subset=['dataQualityGrade'])

In [37]:
state_hist['dataQualityGrade'].unique()

array(['A', 'A+', 'B', 'D', 'C', '#REF!', 'F'], dtype=object)

In [39]:
state_hist['dataQualityGrade'].value_counts()

A+       5675
A        4795
B        4304
C        1096
D         700
F          32
#REF!       6
Name: dataQualityGrade, dtype: int64

In [44]:
state_hist = state_hist[state_hist['dataQualityGrade']!='C']
state_hist = state_hist[state_hist['dataQualityGrade']!='D']
state_hist = state_hist[state_hist['dataQualityGrade']!='F']
state_hist = state_hist[state_hist['dataQualityGrade']!='#REF!']

In [45]:
state_hist['dataQualityGrade'].value_counts()

A+    5675
A     4795
B     4304
Name: dataQualityGrade, dtype: int64

In [47]:
state_hist = state_hist.drop(columns=['dataQualityGrade', 'death', 'deathConfirmed', 'deathProbable', 'hospitalized', 'hospitalizedCumulative',
                        'hospitalizedCurrently', 'inIcuCumulative', 'negative', 'negativeTestsAntibody', 'negativeTestsPeopleAntibody',
                        'negativeTestsViral', 'onVentilatorCumulative', 'positive', 'positiveCasesViral', 'positiveScore',
                        'positiveTestsAntibody', 'positiveTestsAntigen', 'positiveTestsPeopleAntibody', 'positiveTestsPeopleAntigen',
                        'positiveTestsViral', 'recovered'])

In [50]:
state_hist = state_hist.drop(columns=['totalTestEncountersViral', 'totalTestEncountersViralIncrease', 'totalTestResults',
                                     'totalTestResultsIncrease', 'totalTestsAntibody', 'totalTestsAntigen',
                                     'totalTestsPeopleAntibody', 'totalTestsPeopleAntigen', 'totalTestsPeopleViral', 'totalTestsPeopleViralIncrease',
                                     'totalTestsViral', 'totalTestsViralIncrease'])

In [52]:
state_hist = state_hist.fillna(0)

In [53]:
state_hist

,date,state,deathIncrease,hospitalizedIncrease,inIcuCurrently,negativeIncrease,onVentilatorCurrently,positiveIncrease
0,2021-01-15,AK,1,3,0.0,6650,10.0,300
1,2021-01-15,AL,85,313,0.0,10166,0.0,2945
2,2021-01-15,AR,35,95,434.0,12628,226.0,3124
4,2021-01-15,AZ,185,405,1138.0,12383,753.0,9146
5,2021-01-15,CA,637,0,4833.0,276515,0.0,42655
...,...,...,...,...,...,...,...,...
16741,2020-03-23,WI,1,0,0.0,820,0.0,41
16742,2020-03-23,WV,0,0,0.0,59,0.0,4
16743,2020-03-23,WY,0,0,0.0,154,0.0,2
16750,2020-03-22,CO,1,9,0.0,770,0.0,116
16779,2020-03-22,NM,0,0,0.0,599,0.0,8

In [57]:
state_hist.to_csv('cleaned_state_data.csv')